class TestMultipleCatch
{
void m()
{
    throw new ArithmeticException("exception");
}
void n()
{
    m();
}
void p()
{
    try
    {
        n();
    }
    catch(ArithmeticException e)
    {
        System.out.println("exception handled");
    }
}
}
public class Main 
{
public static void main(String args[])
{
    TestMultipleCatch obj1=new TestMultipleCatch();
    obj1.p();
}
}
